// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbrWRyeYadCHVc0fXM2yNEwkIs3p72Mqc',
    appId: '1:572869714577:web:fe19a576581e3897959530',
    messagingSenderId: '572869714577',
    projectId: 'klinikonek-bb5f7',
    authDomain: 'klinikonek-bb5f7.firebaseapp.com',
    storageBucket: 'klinikonek-bb5f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6oEm_P2tODKREj4p6ypOWzDBW0ocl_FA',
    appId: '1:572869714577:android:001c3bf09919c4db959530',
    messagingSenderId: '572869714577',
    projectId: 'klinikonek-bb5f7',
    storageBucket: 'klinikonek-bb5f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2iq780ad08INGTTvwwwqfmk3vemIdzt4',
    appId: '1:572869714577:ios:6f22ea051610224c959530',
    messagingSenderId: '572869714577',
    projectId: 'klinikonek-bb5f7',
    storageBucket: 'klinikonek-bb5f7.appspot.com',
    iosBundleId: 'com.example.klinikonekProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2iq780ad08INGTTvwwwqfmk3vemIdzt4',
    appId: '1:572869714577:ios:902f816fe62ba9e0959530',
    messagingSenderId: '572869714577',
    projectId: 'klinikonek-bb5f7',
    storageBucket: 'klinikonek-bb5f7.appspot.com',
    iosBundleId: 'com.example.klinikonekProject.RunnerTests',
  );
}
